### ISSUE TITLE
Feature Requests for the NotePalettes

### ISSUE THREAD

**Issue by Nevu** [mekkablue/NotePalettes#1]
Hello Mekkablue,

I love this Plugin very much, but I got some feature requests for that:

1) Could it be possible to resize the windows also horizontally,
to get more overview of the notes?

2) Why I have to hit „alt-return“ to make a page makeup? I just like to have an explanation.

3) Is it possible to mark glyphs with a glyphs-note (f.e. the „corner“ like when doing comments insite the glyphs-drawing-window)

thx

**Comment by mekkablue** [comment]
1: no, it is not a window. It is a palette.
2: I do not understand what you mean.
3: you can sort list view by notes. Or have a small script open a tab with all glyphs that have a Note.

**Comment by Nevu** [comment]
-> 2) I have to press „alt-return“, to make a line-break. Why isnt it possible to just hit „return“?

I will try the Scripts, thank you

**Comment by mekkablue** [comment]
2: Because Return finishes and acknowledges the entry. So you have to press ctrl- or opt-Return. Keep in mind that it is just a glyph _note,_ not more. It is meant for small remarks and comments, not lengthy texts.
