### ISSUE TITLE
FontNote  disappeared 

### ISSUE THREAD

**Issue by synthview** [mekkablue/NotePalettes#6]
Hi,
FontNote seems disappeared from the UI in G Version 2.3.1 (919)
GlyphNote shows correctly.

**Comment by mekkablue** [comment]
I am working on a fix. For now, use the Font Note in Font Info.

**Comment by mekkablue** [comment]
Just uploaded an update.

**Comment by synthview** [comment]
G2 freezes when opening/creating any file on Mac os 10.9.5
