### ISSUE TITLE
FontNote hangs Glyphs

### ISSUE THREAD

**Issue by artcs** [mekkablue/NotePalettes#7]
The latest FontNote Palette (2.0) causes Glyphs to hang (spinning beachball) as soon as I try to open a font or open a new Document. Have to force quit, no messages in Console.app.
I'm on OSX 10.9.5, Glyphs 922. If I remove FontNote from Pluginsfolder problem goes away.

**Comment by mekkablue** [comment]
FontNote needs to be rewritten. For now, please resort to editing the font note in _Edit > Font Info > Notes_.

**Comment by artcs** [comment]
Just updated Glyphs to RC2-935 and NotePalettes to latest version. Now GlyphNote hangs Glyphs as well as FontNote on 10.9.5. No crash, just a neverending spinning beachball when opening a document.

**Comment by mekkablue** [comment]
Are you sure you have the latest GlyphNote?
I updated it last week.

**Comment by synthview** [comment]
same 4 me with the last V.

**Comment by mekkablue** [comment]
Glyph Note now works fine for me. Don’t use Font Note for the time being. It still needs to be rewritten.

**Comment by artcs** [comment]
Yes, I'm sure. The version before the updete worked, with the update it stopped working on 10.9.5. GlyphNote.glyphsPaleete Finder Info: Version 2.1.1 Date 2016-11-01, 67608 Bytes.

**Comment by mekkablue** [comment]
Possibly an incompatibility with 10.9. I cannot test on that system, the current version works as expected in Glyphs 935 on Sierra. Anything in the Console?

**Comment by artcs** [comment]
console repeats message

```
07.11.16 14:43:57,476 Glyphs[311]: Problem loading class from plugin bundle: NSBundle </Users/me/Library/Application Support/Glyphs/Plugins/GlyphNote.glyphsPalette> (loaded)
```

endlessly until force quit. I suspect an incompatible nib file.

Analyzing Glyphs with Activity Monitor results in:
[Analyse.txt.zip](https://github.com/mekkablue/NotePalettes/files/575501/Analyse.txt.zip)

**Comment by mekkablue** [comment]
Which other plugins do you have installed? Does it work if you disable all other plugins?

**Comment by artcs** [comment]
No, it's the same when GlyphNote is the only Plugin installed.. Also tried with a fresh useraccount to no avail.

**Comment by mekkablue** [comment]
The .nib is fine, I recompiled it and there was no change in the binary. And I also checked the class references in Info.plist and plugin.py: I couldn’t find anything fishy. Sorry, it may simply not be compatible with 10.9 anymore. I cannot help you.

**Comment by artcs** [comment]
Closing the thread is certainly easier than finding a solution. Too bad.

**Comment by mekkablue** [comment]
I do not have a machine with 10.9 anymore, that is why I cannot help you find a solution unless you upgrade. The code is open source. You are invited to make it compatible with 10.9 yourself. Also, if you are sure that the previous version worked, why don’t you use that one instead?
